"use client";

import {
	Combobox,
	ComboboxChip,
	ComboboxChips,
	ComboboxChipsInput,
	ComboboxContent,
	ComboboxEmpty,
	ComboboxItem,
	ComboboxList,
	ComboboxValue,
} from "../ui/combobox";
import { Label } from "../ui/label";
import { Switch } from "../ui/switch";

export default function TagsChoser({
	setTagsSwitchStatus,
	tagsSwitchStatus,
	updateFilter,
	filters,
}) {
	const tags = [
		"4-koma",
		"Achromatic",
		"Achronological Order",
		"Acrobatics",
		"Acting",
		"Adoption",
		"Advertisement",
		"Afterlife",
		"Age Gap",
		"Age Regression",
		"Agender",
		"Agriculture",
		"Ahegao",
		"Airsoft",
		"Alchemy",
		"Aliens",
		"Alternate Universe",
		"American Football",
		"Amnesia",
		"Amputation",
		"Anachronism",
		"Anal Sex",
		"Ancient China",
		"Angels",
		"Animals",
		"Anthology",
		"Anthropomorphism",
		"Anti-Hero",
		"Archery",
		"Armpits",
		"Aromantic",
		"Arranged Marriage",
		"Artificial Intelligence",
		"Asexual",
		"Ashikoki",
		"Asphyxiation",
		"Assassins",
		"Astronomy",
		"Athletics",
		"Augmented Reality",
		"Autobiographical",
		"Aviation",
		"Badminton",
		"Ballet",
		"Band",
		"Bar",
		"Baseball",
		"Basketball",
		"Battle Royale",
		"Biographical",
		"Bisexual",
		"Blackmail",
		"Board Game",
		"Boarding School",
		"Body Horror",
		"Body Image",
		"Body Swapping",
		"Bondage",
		"Boobjob",
		"Bowling",
		"Boxing",
		"Boys' Love",
		"Brainwashing",
		"Bullying",
		"Butler",
		"Calligraphy",
		"Camping",
		"Cannibalism",
		"Card Battle",
		"Cars",
		"Centaur",
		"Cervix Penetration",
		"CGI",
		"Cheating",
		"Cheerleading",
		"Chibi",
		"Chimera",
		"Chuunibyou",
		"Circus",
		"Class Struggle",
		"Classic Literature",
		"Classical Music",
		"Clone",
		"Coastal",
		"Cohabitation",
		"College",
		"Coming of Age",
		"Conspiracy",
		"Cosmic Horror",
		"Cosplay",
		"Cowboys",
		"Creature Taming",
		"Crime",
		"Criminal Organization",
		"Crossdressing",
		"Crossover",
		"Cult",
		"Cultivation",
		"Cumflation",
		"Cunnilingus",
		"Curses",
		"Cute Boys Doing Cute Things",
		"Cute Girls Doing Cute Things",
		"Cyberpunk",
		"Cyborg",
		"Cycling",
		"Dancing",
		"Death Game",
		"Deepthroat",
		"Defloration",
		"Delinquents",
		"Demons",
		"Denpa",
		"Desert",
		"Detective",
		"DILF",
		"Dinosaurs",
		"Disability",
		"Dissociative Identities",
		"Double Penetration",
		"Dragons",
		"Drawing",
		"Drugs",
		"Dullahan",
		"Dungeon",
		"Dystopian",
		"E-Sports",
		"Eco-Horror",
		"Economics",
		"Educational",
		"Elderly Protagonist",
		"Elf",
		"Ensemble Cast",
		"Environmental",
		"Episodic",
		"Ero Guro",
		"Erotic Piercings",
		"Espionage",
		"Estranged Family",
		"Exhibitionism",
		"Exorcism",
		"Facial",
		"Fairy",
		"Fairy Tale",
		"Fake Relationship",
		"Family Life",
		"Fashion",
		"Feet",
		"Fellatio",
		"Female Harem",
		"Female Protagonist",
		"Femboy",
		"Femdom",
		"Fencing",
		"Filmmaking",
		"Fingering",
		"Firefighters",
		"Fishing",
		"Fisting",
		"Fitness",
		"Flash",
		"Flat Chest",
		"Food",
		"Football",
		"Foreign",
		"Found Family",
		"Fugitive",
		"Full CGI",
		"Full Color",
		"Futanari",
		"Gambling",
		"Gangs",
		"Gekiga",
		"Gender Bending",
		"Ghost",
		"Go",
		"Goblin",
		"Gods",
		"Golf",
		"Gore",
		"Graduation Project",
		"Group Sex",
		"Guns",
		"Gyaru",
		"Hair Pulling",
		"Handball",
		"Handjob",
		"Henshin",
		"Heterosexual",
		"Hikikomori",
		"Hip-hop Music",
		"Historical",
		"Homeless",
		"Horticulture",
		"Human Experimentation",
		"Human Pet",
		"Hypersexuality",
		"Ice Skating",
		"Idol",
		"Incest",
		"Indigenous Cultures",
		"Inn",
		"Inseki",
		"Interspecies",
		"Irrumatio",
		"Isekai",
		"Iyashikei",
		"Jazz Music",
		"Josei",
		"Judo",
		"Kabuki",
		"Kaiju",
		"Karuta",
		"Kemonomimi",
		"Kids",
		"Kingdom Management",
		"Konbini",
		"Kuudere",
		"Lacrosse",
		"Lactation",
		"Language Barrier",
		"Large Breasts",
		"LGBTQ+ Themes",
		"Long Strip",
		"Lost Civilization",
		"Love Triangle",
		"Mafia",
		"Magic",
		"Mahjong",
		"Maids",
		"Makeup",
		"Male Harem",
		"Male Pregnancy",
		"Male Protagonist",
		"Manzai",
		"Marriage",
		"Martial Arts",
		"Masochism",
		"Masturbation",
		"Matchmaking",
		"Mating Press",
		"Matriarchy",
		"Medicine",
		"Medieval",
		"Memory Manipulation",
		"Mermaid",
		"Meta",
		"Metal Music",
		"MILF",
		"Military",
		"Mixed Gender Harem",
		"Mixed Media",
		"Modeling",
		"Monster Boy",
		"Monster Girl",
		"Mopeds",
		"Motorcycles",
		"Mountaineering",
		"Musical Theater",
		"Mythology",
		"Nakadashi",
		"Natural Disaster",
		"Necromancy",
		"Nekomimi",
		"Netorare",
		"Netorase",
		"Netori",
		"Ninja",
		"No Dialogue",
		"Noir",
		"Non-fiction",
		"Nudity",
		"Nun",
		"Office",
		"Office Lady",
		"Oiran",
		"Ojou-sama",
		"Omegaverse",
		"Orphan",
		"Otaku Culture",
		"Outdoor Activities",
		"Oyakodon",
		"Pandemic",
		"Parenthood",
		"Parkour",
		"Parody",
		"Pet Play",
		"Philosophy",
		"Photography",
		"Pirates",
		"Poker",
		"Police",
		"Politics",
		"Polyamorous",
		"Post-Apocalyptic",
		"POV",
		"Pregnancy",
		"Primarily Adult Cast",
		"Primarily Animal Cast",
		"Primarily Child Cast",
		"Primarily Female Cast",
		"Primarily Male Cast",
		"Primarily Teen Cast",
		"Prison",
		"Prostitution",
		"Proxy Battle",
		"Psychosexual",
		"Public Sex",
		"Puppetry",
		"Rakugo",
		"Rape",
		"Real Robot",
		"Rehabilitation",
		"Reincarnation",
		"Religion",
		"Rescue",
		"Restaurant",
		"Revenge",
		"Reverse Isekai",
		"Rimjob",
		"Robots",
		"Rock Music",
		"Rotoscoping",
		"Royal Affairs",
		"Rugby",
		"Rural",
		"Sadism",
		"Samurai",
		"Satire",
		"Scat",
		"School",
		"School Club",
		"Scissoring",
		"Scuba Diving",
		"Seinen",
		"Sex Toys",
		"Shapeshifting",
		"Shimaidon",
		"Ships",
		"Shogi",
		"Short-Form Chapter",
		"Shoujo",
		"Shounen",
		"Shrine Maiden",
		"Skateboarding",
		"Skeleton",
		"Slapstick",
		"Slavery",
		"Snowscape",
		"Software Development",
		"Space",
		"Space Opera",
		"Spearplay",
		"Squirting",
		"Steampunk",
		"Stop Motion",
		"Succubus",
		"Suicide",
		"Sumata",
		"Sumo",
		"Super Power",
		"Super Robot",
		"Superhero",
		"Surfing",
		"Surreal Comedy",
		"Survival",
		"Swapping",
		"Sweat",
		"Swimming",
		"Swordplay",
		"Table Tennis",
		"Tanks",
		"Tanned Skin",
		"Teacher",
		"Teens' Love",
		"Tennis",
		"Tentacles",
		"Terrorism",
		"Threesome",
		"Time Loop",
		"Time Manipulation",
		"Time Skip",
		"Tokusatsu",
		"Tomboy",
		"Torture",
		"Tragedy",
		"Trains",
		"Transgender",
		"Travel",
		"Triads",
		"Tsundere",
		"Twins",
		"Unrequited Love",
		"Urban",
		"Urban Fantasy",
		"Vampire",
		"Vertical Video",
		"Veterinarian",
		"Video Games",
		"Vikings",
		"Villainess",
		"Virginity",
		"Virtual World",
		"Vocal Synth",
		"Volleyball",
		"Vore",
		"Voyeur",
		"VTuber",
		"War",
		"Watersports",
		"Werewolf",
		"Wilderness",
		"Witch",
		"Work",
		"Wrestling",
		"Writing",
		"Wuxia",
		"Yakuza",
		"Yandere",
		"Youkai",
		"Yuri",
		"Zombie",
		"Zoophilia",
	];

	const availableTagsToShow = tags.filter(
		(tag) => !filters.hide_selected_tags?.includes(tag),
	);
	const availableTagsToHide = tags.filter(
		(tag) => !filters.show_selected_tags?.includes(tag),
	);

	return (
		<div className="space-y-4 p-1">
			<div className="flex items-center justify-between px-1">
				<Label
					htmlFor="showHideTag"
					className="text-[12px] text-slate-400 cursor-pointer"
				>
					{tagsSwitchStatus ? "Show" : "Hide"} selected tags
				</Label>
				<Switch
					checked={tagsSwitchStatus}
					onCheckedChange={() =>
						tagsSwitchStatus
							? setTagsSwitchStatus(false)
							: setTagsSwitchStatus(true)
					}
					id="showHideTag"
					className="data-[state=checked]:bg-violet-600 scale-75 origin-right"
				/>
			</div>

			<Combobox
				items={tagsSwitchStatus ? availableTagsToShow : availableTagsToHide}
				multiple
				value={
					tagsSwitchStatus
						? (filters.show_selected_tags ?? [])
						: (filters.hide_selected_tags ?? [])
				}
				onValueChange={(value) =>
					tagsSwitchStatus
						? updateFilter("show_selected_tags", value)
						: updateFilter("hide_selected_tags", value)
				}
			>
				<ComboboxChips className="w-full bg-white/[0.02] border-white/[0.08] rounded-xl p-2 min-h-[44px] transition-all focus-within:border-violet-500/40 shadow-inner">
					<ComboboxValue>
						{(tagsSwitchStatus
							? filters.show_selected_tags
							: filters.hide_selected_tags
						)?.map((item) => (
							<ComboboxChip
								key={item}
								className={
									"bg-violet-500/10 border-violet-500/30 text-violet-300 hover:bg-violet-500/20 transition-colors"
								}
							>
								{item}
							</ComboboxChip>
						))}
					</ComboboxValue>
					<ComboboxChipsInput
						placeholder="Search tags..."
						className="text-[11px] text-slate-200 placeholder:text-slate-600 bg-transparent border-none focus:ring-0"
					/>
				</ComboboxChips>
				<ComboboxContent className="bg-[#0f172a] border-white/[0.1] shadow-2xl max-h-60 overflow-hidden">
					<ComboboxEmpty className="text-xs text-slate-500 p-4">
						No tags found.
					</ComboboxEmpty>
					<ComboboxList className="custom-filters-scrollbar overflow-y-auto">
						{(item) => (
							<ComboboxItem
								key={item}
								value={item}
								className="text-xs text-slate-300 data-[highlighted]:bg-violet-500/20 data-[highlighted]:text-violet-200 cursor-pointer"
							>
								{item}
							</ComboboxItem>
						)}
					</ComboboxList>
				</ComboboxContent>
			</Combobox>
		</div>
	);
}
