"use client";

import {
	Combobox,
	ComboboxChip,
	ComboboxChips,
	ComboboxChipsInput,
	ComboboxContent,
	ComboboxEmpty,
	ComboboxItem,
	ComboboxList,
	ComboboxValue,
	useComboboxAnchor,
} from "../ui/combobox";
import { Label } from "../ui/label";
import { Switch } from "../ui/switch";

const TAGS = [
	"Male Protagonist",
	"Female Protagonist",
	"Heterosexual",
	"School",
	"Shounen",
	"Tragedy",
	"Magic",
	"Seinen",
	"Nudity",
	"Primarily Adult Cast",
	"Primarily Female Cast",
	"Primarily Teen Cast",
	"Ensemble Cast",
	"Love Triangle",
	"Female Harem",
	"Urban Fantasy",
	"Super Power",
	"Isekai",
	"Full Color",
	"Coming of Age",
	"LGBTQ+ Themes",
	"Swordplay",
	"Gore",
	"Urban",
	"Kuudere",
	"Demons",
	"Primarily Male Cast",
	"Tsundere",
	"Time Skip",
	"Episodic",
	"Revenge",
	"Philosophy",
	"Anti-Hero",
	"Guns",
	"Work",
	"Reincarnation",
	"Yuri",
	"Age Gap",
	"CGI",
	"War",
	"Bullying",
	"Gods",
	"School Club",
	"Foreign",
	"Politics",
	"Time Manipulation",
	"Historical",
	"Crossdressing",
	"Cute Girls Doing Cute Things",
	"Slapstick",
	"Crime",
	"Military",
	"Family Life",
	"Conspiracy",
	"Martial Arts",
	"Parody",
	"Suicide",
	"Animals",
	"Shoujo",
	"Body Horror",
	"Amnesia",
	"Surreal Comedy",
	"Yandere",
	"Meta",
	"Rural",
	"Tomboy",
	"Found Family",
	"Dragons",
	"Boys' Love",
	"Henshin",
	"Aliens",
	"Rape",
	"Iyashikei",
	"Kemonomimi",
	"Twins",
	"Travel",
	"Long Strip",
	"Survival",
	"Memory Manipulation",
	"Medieval",
	"Unrequited Love",
	"Bisexual",
	"Food",
	"Robots",
	"Ghost",
	"Post-Apocalyptic",
	"Monster Girl",
	"Mythology",
	"Shapeshifting",
	"Assassins",
	"Adoption",
	"Idol",
	"Primarily Child Cast",
	"Delinquents",
	"Alternate Universe",
	"Maids",
	"Royal Affairs",
	"Gender Bending",
	"Age Regression",
	"Vampire",
	"Disability",
	"Dissociative Identities",
	"Detective",
	"Elf",
	"Ojou-sama",
	"Video Games",
	"Artificial Intelligence",
	"Chibi",
	"Police",
	"Tanned Skin",
	"College",
	"Dystopian",
	"Otaku Culture",
	"Religion",
	"Orphan",
	"Rehabilitation",
	"Space",
	"Fugitive",
	"Teacher",
	"Youkai",
	"Anthropomorphism",
	"Dungeon",
	"Large Breasts",
	"Slavery",
	"Witch",
	"Drugs",
	"Acting",
	"Terrorism",
	"Educational",
	"Cultivation",
	"Josei",
	"Marriage",
	"Kaiju",
	"Cosmic Horror",
	"Drawing",
	"Cult",
	"Nekomimi",
	"Denpa",
	"Gyaru",
	"Incest",
	"Achronological Order",
	"Cute Boys Doing Cute Things",
	"Virtual World",
	"Gangs",
	"Lost Civilization",
	"Zombie",
	"Fellatio",
	"Cohabitation",
	"Curses",
	"Battle Royale",
	"Transgender",
	"Samurai",
	"Hikikomori",
	"Real Robot",
	"Archery",
	"Angels",
	"Yakuza",
	"Afterlife",
	"Villainess",
	"Male Harem",
	"Torture",
	"Ships",
	"Body Swapping",
	"Ninja",
	"Cyberpunk",
	"Coastal",
	"Death Game",
	"Environmental",
	"Femboy",
	"Super Robot",
	"Class Struggle",
	"Masturbation",
	"Satire",
	"Office Lady",
	"Language Barrier",
	"Superhero",
	"Chuunibyou",
	"Kids",
	"Espionage",
	"Estranged Family",
	"Anachronism",
	"Tokusatsu",
	"Polyamorous",
	"Motorcycles",
	"Band",
	"Monster Boy",
	"Medicine",
	"Outdoor Activities",
	"Anal Sex",
	"Arranged Marriage",
	"Writing",
	"Cyborg",
	"Clone",
	"Parenthood",
	"Economics",
	"Nakadashi",
	"Trains",
	"Cosplay",
	"Spearplay",
	"Mafia",
	"Psychosexual",
	"Kingdom Management",
	"Exorcism",
	"Butler",
	"Baseball",
	"Boarding School",
	"Skeleton",
	"Cannibalism",
	"Desert",
	"Necromancy",
	"Dancing",
	"Athletics",
	"Goblin",
	"Handjob",
	"Steampunk",
	"Snowscape",
	"Full CGI",
	"Gambling",
	"Photography",
	"Cars",
	"Bar",
	"Wuxia",
	"Fairy",
	"Shrine Maiden",
	"Creature Taming",
	"Fairy Tale",
	"Office",
	"Aviation",
	"Pirates",
	"Musical Theater",
	"Classic Literature",
	"Cunnilingus",
	"4-koma",
	"Agriculture",
	"Proxy Battle",
	"Werewolf",
	"Nun",
	"Basketball",
	"Agender",
	"Prison",
	"POV",
	"Time Loop",
	"Bondage",
	"Public Sex",
	"Threesome",
	"Defloration",
	"MILF",
	"Netorare",
	"Fashion",
	"Mermaid",
	"Criminal Organization",
	"Restaurant",
	"Space Opera",
	"Swimming",
	"Succubus",
	"Anthology",
	"Fake Relationship",
	"Crossover",
	"Pandemic",
	"Sadism",
	"Pregnancy",
	"Software Development",
	"Inseki",
	"Alchemy",
	"Virginity",
	"Feet",
	"Card Battle",
	"Boxing",
	"Astronomy",
	"Facial",
	"Noir",
	"Prostitution",
	"Group Sex",
	"Fishing",
	"Boobjob",
	"Asexual",
	"Femdom",
	"Football",
	"Ahegao",
	"Sex Toys",
	"Chimera",
	"Fitness",
	"Volleyball",
	"Rock Music",
	"Augmented Reality",
	"Blackmail",
	"Deepthroat",
	"Wilderness",
	"Mixed Media",
	"Homeless",
	"Masochism",
	"Aromantic",
	"Mixed Gender Harem",
	"Tanks",
	"Circus",
	"Mahjong",
	"Dinosaurs",
	"Horticulture",
	"Reverse Isekai",
	"Tennis",
	"Body Image",
	"Classical Music",
	"Rimjob",
	"Watersports",
	"Mopeds",
	"Primarily Animal Cast",
	"Rotoscoping",
	"Human Pet",
	"Squirting",
	"Matriarchy",
	"Netori",
	"Makeup",
	"Dullahan",
	"Board Game",
	"Autobiographical",
	"Wrestling",
	"Hypersexuality",
	"Exhibitionism",
	"Natural Disaster",
	"No Dialogue",
	"Eco-Horror",
	"Inn",
	"Achromatic",
	"Filmmaking",
	"Indigenous Cultures",
	"Cheating",
	"Rescue",
	"Shogi",
	"E-Sports",
	"Ancient China",
	"Camping",
	"Acrobatics",
	"Elderly Protagonist",
	"VTuber",
	"Voyeur",
	"Flash",
	"Judo",
	"Oiran",
	"Ero Guro",
	"Tentacles",
	"Konbini",
	"Cycling",
	"Interspecies",
	"Vore",
	"Amputation",
	"Modeling",
	"Triads",
	"Ashikoki",
	"Calligraphy",
	"Centaur",
	"Table Tennis",
	"Cowboys",
	"Poker",
	"Irrumatio",
	"Flat Chest",
	"Lactation",
	"Scissoring",
	"Ice Skating",
	"Rakugo",
	"Advertisement",
	"Hip-hop Music",
	"Badminton",
	"Scuba Diving",
	"Biographical",
	"Mountaineering",
	"Cheerleading",
	"Airsoft",
	"Metal Music",
	"Sumata",
	"Human Experimentation",
	"Firefighters",
	"Karuta",
	"Omegaverse",
	"Bowling",
	"Surfing",
	"Parkour",
	"Stop Motion",
	"DILF",
	"Teens' Love",
	"Fingering",
	"Armpits",
	"Matchmaking",
	"Vocal Synth",
	"Double Penetration",
	"Netorase",
	"Futanari",
	"Skateboarding",
	"Scat",
	"Brainwashing",
	"Male Pregnancy",
	"Non-fiction",
	"Short-Form Chapter",
	"Ballet",
	"Golf",
	"Sweat",
	"Shimaidon",
	"Go",
	"American Football",
	"Vikings",
	"Rugby",
	"Fencing",
	"Sumo",
	"Asphyxiation",
	"Jazz Music",
	"Veterinarian",
	"Oyakodon",
	"Pet Play",
	"Gekiga",
	"Puppetry",
	"Manzai",
	"Zoophilia",
	"Lacrosse",
	"Mating Press",
	"Kabuki",
	"Handball",
	"Cumflation",
	"Hair Pulling",
	"Erotic Piercings",
	"Cervix Penetration",
	"Graduation Project",
	"Fisting",
];

export default function TagsChoser({
	setTagsSwitchStatus,
	tagsSwitchStatus,
	updateFilter,
	filters,
}) {
	const anchorRef = useComboboxAnchor();

	const availableTagsToShow = TAGS.filter(
		(tag) => !filters.hide_selected_tags?.includes(tag),
	);
	const availableTagsToHide = TAGS.filter(
		(tag) => !filters.show_selected_tags?.includes(tag),
	);

	return (
		<div className="space-y-4 p-1" ref={anchorRef}>
			<div className="flex items-center justify-between px-1">
				<Label
					htmlFor="showHideTag"
					className="text-[12px] text-slate-400 cursor-pointer"
				>
					{tagsSwitchStatus ? "Show only" : "Hide all"} selected tags
				</Label>
				<Switch
					checked={tagsSwitchStatus}
					onCheckedChange={() =>
						tagsSwitchStatus
							? setTagsSwitchStatus(false)
							: setTagsSwitchStatus(true)
					}
					id="showHideTag"
					className="data-[state=checked]:bg-violet-600 scale-75 origin-right"
				/>
			</div>
			<Combobox
				items={tagsSwitchStatus ? availableTagsToShow : availableTagsToHide}
				multiple
				value={
					tagsSwitchStatus
						? (filters.show_selected_tags ?? [])
						: (filters.hide_selected_tags ?? [])
				}
				onValueChange={(value) =>
					tagsSwitchStatus
						? updateFilter("show_selected_tags", value)
						: updateFilter("hide_selected_tags", value)
				}
			>
				<ComboboxChips className="w-full bg-white/[0.02] border-white/[0.08] rounded-xl p-2 min-h-[44px] transition-all focus-within:border-violet-500/40 shadow-inner">
					<ComboboxValue>
						{(tagsSwitchStatus
							? filters.show_selected_tags
							: filters.hide_selected_tags
						)?.map((item) => (
							<ComboboxChip
								key={item}
								className={
									"bg-violet-500/10 border-violet-500/30 text-violet-300 hover:bg-violet-500/20 transition-colors"
								}
							>
								{item}
							</ComboboxChip>
						))}
					</ComboboxValue>
					<ComboboxChipsInput
						placeholder="Search tags..."
						className="text-[11px] text-white placeholder:text-slate-400 bg-transparent border-none focus:ring-0"
					/>
				</ComboboxChips>
				<ComboboxContent
					anchor={anchorRef}
					className="bg-[#0f172a] border-white/[0.1] shadow-2xl max-h-60 overflow-hidden"
				>
					<ComboboxEmpty className="text-xs text-slate-500 p-4">
						No tags found.
					</ComboboxEmpty>
					<ComboboxList className="custom-filters-scrollbar overflow-y-auto">
						{(item) => (
							<ComboboxItem
								key={item}
								value={item}
								className="text-xs text-slate-300 data-[highlighted]:bg-violet-500/20 data-[highlighted]:text-violet-200 cursor-pointer"
							>
								{item}
							</ComboboxItem>
						)}
					</ComboboxList>
				</ComboboxContent>
			</Combobox>
		</div>
	);
}
