"use client";

import {
	Combobox,
	ComboboxChip,
	ComboboxChips,
	ComboboxChipsInput,
	ComboboxContent,
	ComboboxEmpty,
	ComboboxItem,
	ComboboxList,
	ComboboxValue,
	useComboboxAnchor,
} from "../ui/combobox";
import { Label } from "../ui/label";
import { Switch } from "../ui/switch";

const TAGS = [
	"Male Protagonist",
	"Female Protagonist",
	"School",
	"Heterosexual",
	"Shounen",
	"Tragedy",
	"Magic",
	"Seinen",
	"Nudity",
	"Primarily Adult Cast",
	"Primarily Teen Cast",
	"Ensemble Cast",
	"Super Power",
	"Urban Fantasy",
	"Full Color",
	"Long Strip",
	"Swordplay",
	"Gore",
	"Urban",
	"Kuudere",
	"CGI",
	"Age Gap",
	"War",
	"Bullying",
	"Gods",
	"Guns",
	"Time Manipulation",
	"Historical",
	"Slapstick",
	"Military",
	"Medicine",
	"Philosophy",
	"Tsundere",
	"Coming of Age",
	"Villainess",
	"Reincarnation",
	"Idol",
	"Dystopian",
	"Anti-Hero",
	"Found Family",
	"Work",
	"Shoujo",
	"Tomboy",
	"Survival",
	"Post-Apocalyptic",
	"Family Life",
	"Delinquents",
	"Cyberpunk",
	"Dragons",
	"Bisexual",
	"Crossdressing",
	"Aliens",
	"Gender Bending",
	"Maids",
	"Shapeshifting",
	"Amnesia",
	"Body Horror",
	"Yandere",
	"Conspiracy",
	"Cosmic Horror",
	"Dungeon",
	"Suicide",
	"Ghosts",
	"Martial Arts",
	"Otaku Culture",
	"Robots",
	"Music",
	"Space",
	"Primarily Male Cast",
	"Rural",
	"Video Games",
	"Vampire",
	"Artificial Intelligence",
	"Comedy",
	"Monsters",
	"Drama",
	"Josei",
	"School Club",
	"Teacher",
	"Police",
	"Threesome",
	"Superheroes",
	"Idols",
	"Food",
	"Demons",
	"Super Robot",
	"Romance",
	"Gangs",
	"Fantasy",
	"Action",
	"Mecha",
	"Ecchi",
	"Harem",
	"Slice of Life",
	"Adventure",
	"Mystery",
	"Sci-Fi",
	"Psychological",
	"Sports",
	"Horror",
	"Thriller",
	"Supernatural",
	"Yuri",
	"Boys' Love",
	"Henshin",
	"Mahjong",
	"Cycling",
	"Dancing",
	"Drawing",
	"Fashion",
	"Trains",
	"Photography",
	"Animals",
	"Butler",
	"Time Loop",
	"Virtual World",
	"Witch",
	"Mythology",
	"Angels",
	"Exorcism",
	"Shrine Maiden",
	"Ninja",
	"Samurai",
	"Yakuza",
	"Assassins",
	"Detective",
	"Law",
	"Crime",
	"Mafia",
	"Prison",
	"Fugitive",
	"Terrorism",
	"Villain",
	"Dark Comedy",
	"Cute Girls Doing Cute Things",
	"Cute Boys Doing Cute Things",
	"Cosplay",
	"Band",
	"Musical Theater",
	"Classical Music",
	"Rock Music",
	"Metal Music",
	"Jazz Music",
	"Hip-hop Music",
	"Vocal Synth",
	"VTuber",
	"Filmmaking",
	"Acting",
	"Writing",
	"Calligraphy",
	"Makeup",
	"Modeling",
	"Architecture",
	"Agriculture",
	"Horticulture",
	"Veterinarian",
	"Software Development",
	"Board Game",
	"Card Battle",
	"Shogi",
	"Go",
	"Poker",
	"Gambling",
	"E-Sports",
	"Track and Field",
	"Swimming",
	"Scuba Diving",
	"Surfing",
	"Fishing",
	"Boating",
	"Sailing",
	"Rowing",
	"Canoeing",
	"Kayaking",
	"Rafting",
	"Windsurfing",
	"Kitesurfing",
	"Paddleboarding",
	"Water Polo",
	"Synchronized Swimming",
	"Diving",
	"Ice Skating",
	"Figure Skating",
	"Speed Skating",
	"Short Track",
	"Ice Hockey",
	"Curling",
	"Skiing",
	"Snowboarding",
	"Bobsleigh",
	"Luge",
	"Skeleton",
	"Ski Jumping",
	"Freestyle Skiing",
	"Biathlon",
	"Cross-Country Skiing",
	"Nordic Combined",
	"4-koma",
	"Achromatic",
	"Achronological Order",
	"Acrobatics",
	"Adoption",
	"Advertisement",
	"Afterlife",
	"Age Regression",
	"Agender",
	"Ahegao",
	"Airsoft",
	"Alchemy",
	"Alternate Universe",
	"American Football",
	"Amputation",
	"Anachronism",
	"Anal Sex",
	"Ancient China",
	"Anthology",
	"Anthropomorphism",
	"Archery",
	"Armpits",
	"Aromantic",
	"Arranged Marriage",
	"Asexual",
	"Ashikoki",
	"Asphyxiation",
	"Astronomy",
	"Athletics",
	"Augmented Reality",
	"Autobiographical",
	"Aviation",
	"Badminton",
	"Ballet",
	"Bar",
	"Baseball",
	"Basketball",
	"Battle Royale",
	"Biographical",
	"Blackmail",
	"Boarding School",
	"Body Image",
	"Body Swapping",
	"Bondage",
	"Boobjob",
	"Bowling",
	"Boxing",
	"Brainwashing",
	"Camping",
	"Cannibalism",
	"Cars",
	"Centaur",
	"Cervix Penetration",
	"Cheating",
	"Cheerleading",
	"Chibi",
	"Chimera",
	"Chuunibyou",
	"Circus",
	"Class Struggle",
	"Classic Literature",
	"Clone",
	"Coastal",
	"Cohabitation",
	"College",
	"Cowboys",
	"Creature Taming",
	"Criminal Organization",
	"Crossover",
	"Cult",
	"Cultivation",
	"Cumflation",
	"Cunnilingus",
	"Curses",
	"Death Game",
	"Deepthroat",
	"Defloration",
	"Denpa",
	"Desert",
	"DILF",
	"Dinosaurs",
	"Disability",
	"Dissociative Identities",
	"Double Penetration",
	"Drugs",
	"Dullahan",
	"E-Sports",
	"Eco-Horror",
	"Economics",
	"Educational",
	"Elderly Protagonist",
	"Elf",
	"Environmental",
	"Episodic",
	"Ero Guro",
	"Erotic Piercings",
	"Espionage",
	"Estranged Family",
	"Exhibitionism",
	"Facial",
	"Fairy",
	"Fairy Tale",
	"Fake Relationship",
	"Feet",
	"Fellatio",
	"Femboy",
	"Femdom",
	"Fencing",
	"Fingering",
	"Firefighters",
	"Fisting",
	"Fitness",
	"Flash",
	"Flat Chest",
	"Football",
	"Foreign",
	"Futanari",
	"Gekiga",
	"Ghost",
	"Goblin",
	"Golf",
	"Graduation Project",
	"Group Sex",
	"Gyaru",
	"Hair Pulling",
	"Handball",
	"Handjob",
	"Hikikomori",
	"Homeless",
	"Human Experimentation",
	"Human Pet",
	"Hypersexuality",
	"Incest",
	"Indigenous Cultures",
	"Inn",
	"Inseki",
	"Interspecies",
	"Irrumatio",
	"Isekai",
	"Iyashikei",
	"Judo",
	"Kabuki",
	"Kaiju",
	"Karuta",
	"Kemonomimi",
	"Kids",
	"Kingdom Management",
	"Konbini",
	"Lacrosse",
	"Lactation",
	"Language Barrier",
	"Large Breasts",
	"LGBTQ+ Themes",
	"Lost Civilization",
	"Love Triangle",
	"Male Pregnancy",
	"Manzai",
	"Marriage",
	"Masochism",
	"Masturbation",
	"Matchmaking",
	"Mating Press",
	"Matriarchy",
	"Medieval",
	"Memory Manipulation",
	"Mermaid",
	"Meta",
	"MILF",
	"Mixed Gender Harem",
	"Mixed Media",
	"Monster Boy",
	"Monster Girl",
	"Mopeds",
	"Motorcycles",
	"Mountaineering",
	"Mythology",
	"Nakadashi",
	"Natural Disaster",
	"Necromancy",
	"Nekomimi",
	"Netorare",
	"Netorase",
	"Netori",
	"No Dialogue",
	"Noir",
	"Non-fiction",
	"Nun",
	"Office",
	"Office Lady",
	"Oiran",
	"Ojou-sama",
	"Omegaverse",
	"Orphan",
	"Outdoor Activities",
	"Oyakodon",
	"Pandemic",
	"Parenthood",
	"Parkour",
	"Parody",
	"Pet Play",
	"Pirates",
	"Polyamorous",
	"POV",
	"Pregnancy",
	"Primarily Animal Cast",
	"Primarily Child Cast",
	"Primarily Female Cast",
	"Primarily Teen Cast",
	"Prostitution",
	"Proxy Battle",
	"Psychosexual",
	"Public Sex",
	"Puppetry",
	"Rakugo",
	"Rape",
	"Real Robot",
	"Rehabilitation",
	"Religion",
	"Rescue",
	"Restaurant",
	"Revenge",
	"Reverse Isekai",
	"Rimjob",
	"Rotoscoping",
	"Royal Affairs",
	"Rugby",
	"Scat",
	"Scissoring",
	"Sex Toys",
	"Shimaidon",
	"Ships",
	"Short-Form Chapter",
	"Skeleton",
	"Slavery",
	"Snowscape",
	"Space Opera",
	"Spearplay",
	"Squirting",
	"Steampunk",
	"Stop Motion",
	"Succubus",
	"Sumata",
	"Sumo",
	"Superhero",
	"Swapping",
	"Sweat",
	"Tanks",
	"Tanned Skin",
	"Teens' Love",
	"Tennis",
	"Tentacles",
	"Threesome",
	"Time Skip",
	"Tokusatsu",
	"Torture",
	"Transgender",
	"Travel",
	"Triads",
	"Twins",
	"Unrequited Love",
	"Vampire",
	"Vertical Video",
	"Vikings",
	"Virginity",
	"Vore",
	"Voyeur",
	"Watersports",
	"Werewolf",
	"Wilderness",
	"Wrestling",
	"Wuxia",
	"Youkai",
	"Zombie",
	"Zoophilia",
];

export default function TagsChoser({
	setTagsSwitchStatus,
	tagsSwitchStatus,
	updateFilter,
	filters,
}) {
	const anchorRef = useComboboxAnchor();

	const availableTagsToShow = TAGS.filter(
		(tag) => !filters.hide_selected_tags?.includes(tag),
	);
	const availableTagsToHide = TAGS.filter(
		(tag) => !filters.show_selected_tags?.includes(tag),
	);

	return (
		<div className="space-y-4 p-1" ref={anchorRef}>
			<div className="flex items-center justify-between px-1">
				<Label
					htmlFor="showHideTag"
					className="text-[12px] text-slate-400 cursor-pointer"
				>
					{tagsSwitchStatus ? "Show only" : "Hide all"} selected tags
				</Label>
				<Switch
					checked={tagsSwitchStatus}
					onCheckedChange={() =>
						tagsSwitchStatus
							? setTagsSwitchStatus(false)
							: setTagsSwitchStatus(true)
					}
					id="showHideTag"
					className="data-[state=checked]:bg-violet-600 scale-75 origin-right"
				/>
			</div>
			<Combobox
				items={tagsSwitchStatus ? availableTagsToShow : availableTagsToHide}
				multiple
				value={
					tagsSwitchStatus
						? (filters.show_selected_tags ?? [])
						: (filters.hide_selected_tags ?? [])
				}
				onValueChange={(value) =>
					tagsSwitchStatus
						? updateFilter("show_selected_tags", value)
						: updateFilter("hide_selected_tags", value)
				}
			>
				<ComboboxChips className="w-full bg-white/[0.02] border-white/[0.08] rounded-xl p-2 min-h-[44px] transition-all focus-within:border-violet-500/40 shadow-inner">
					<ComboboxValue>
						{(tagsSwitchStatus
							? filters.show_selected_tags
							: filters.hide_selected_tags
						)?.map((item) => (
							<ComboboxChip
								key={item}
								className={
									"bg-violet-500/10 border-violet-500/30 text-violet-300 hover:bg-violet-500/20 transition-colors"
								}
							>
								{item}
							</ComboboxChip>
						))}
					</ComboboxValue>
					<ComboboxChipsInput
						placeholder="Search tags..."
						className="text-[11px] text-white placeholder:text-slate-400 bg-transparent border-none focus:ring-0"
					/>
				</ComboboxChips>
				<ComboboxContent
					anchor={anchorRef}
					className="bg-[#0f172a] border-white/[0.1] shadow-2xl max-h-60 overflow-hidden"
				>
					<ComboboxEmpty className="text-xs text-slate-500 p-4">
						No tags found.
					</ComboboxEmpty>
					<ComboboxList className="custom-filters-scrollbar overflow-y-auto">
						{(item) => (
							<ComboboxItem
								key={item}
								value={item}
								className="text-xs text-slate-300 data-[highlighted]:bg-violet-500/20 data-[highlighted]:text-violet-200 cursor-pointer"
							>
								{item}
							</ComboboxItem>
						)}
					</ComboboxList>
				</ComboboxContent>
			</Combobox>
		</div>
	);
}
